### ISSUE TITLE
Document new NATS server configuration for using jetstream

### ISSUE THREAD

**Issue by ao508** [mskcc/cmo-metadb#227]
Update the configuration that is already checked into the MSK GitHub cmo-metadb-configuration repository

- tls commands need to change
- prob dont need the id/pass for stan anymore since it's being dropped
- update docs checked in to reflect new nats cmd line args

a way to configure duration of a message so that it's held long enough for every (subscribed) client to receive it. 

What are the minimum properties we need to set?

**Comment by ao508** [comment]
@divyamadala30 add details here

**Comment by divyamadala30** [comment]
Subjects to consume METADB.*
Storage backend file
Retention Policy Limits
Discard Policy Old
Stream Messages Limit -1
Message size limit -1
Maximum message age limit -1
Maximum individual message size -1
Duplicate tracking time window 2m
Replicas 1

**Comment by divyamadala30** [comment]
Available subjects: METADB.cmo-request, METADB.igo-request, METADB.consistency-checker-request

**Comment by ao508** [comment]
k8s consumers:

https://docs.nats.io/jetstream/configuration_mgmt/kubernetes_controller

example creating stream and a few consumers

```
apiVersion: jetstream.nats.io/v1beta1
kind: Stream
metadata:
  name: mystream
spec:
  name: mystream
  subjects: ["orders.*"]
  storage: memory
  maxAge: 1h
---
apiVersion: jetstream.nats.io/v1beta1
kind: Consumer
metadata:
  name: my-push-consumer
spec:
  streamName: mystream
  durableName: my-push-consumer
  deliverSubject: my-push-consumer.orders
  deliverPolicy: last
  ackPolicy: none
  replayPolicy: instant
---
apiVersion: jetstream.nats.io/v1beta1
kind: Consumer
metadata:
  name: my-pull-consumer
spec:
  streamName: mystream
  durableName: my-pull-consumer
  deliverPolicy: all
  filterSubject: orders.received
  maxDeliver: 20
  ackPolicy: explicit
```

https://github.com/nats-io/nack#getting-started


example config file for k8s deployment

https://raw.githubusercontent.com/nats-io/k8s/master/nats-server/nats-js-leaf.yml

helm charts for nats

https://nats-io.github.io/k8s/#helm-charts-for-nats <-- link doesnt work

https://artifacthub.io/packages/helm/nats/nats
